import { Dog } from "./src/types/dog.types";

const data: Dog[] = [
  {
    name: "Affenpinscher",
    img: "https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg",
    height: "23 - 29",
    weight: "23 - 29",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Stubborn",
      "Curious",
      "Playful",
      "Adventurous",
      "Active",
      "Fun-loving",
    ],
    breedGroup: "Toy",
    id: 1,
  },
  {
    name: "Afghan Hound",
    img: "https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg",
    height: "64 - 69",
    weight: "64 - 69",
    lifeSpan: "10 - 13 years",
    temperaments: ["Aloof", "Clownish", "Dignified", "Independent", "Happy"],
    breedGroup: "Hound",
    id: 2,
  },
  {
    name: "African Hunting Dog",
    img: "https://cdn2.thedogapi.com/images/rkiByec47.jpg",
    height: "76",
    weight: "76",
    lifeSpan: "11 years",
    temperaments: ["Wild", "Hardworking", "Dutiful"],
    breedGroup: "Unknown",
    id: 3,
  },
  {
    name: "Airedale Terrier",
    img: "https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg",
    height: "53 - 58",
    weight: "53 - 58",
    lifeSpan: "10 - 13 years",
    temperaments: [
      "Outgoing",
      "Friendly",
      "Alert",
      "Confident",
      "Intelligent",
      "Courageous",
    ],
    breedGroup: "Terrier",
    id: 4,
  },
  {
    name: "Akbash Dog",
    img: "https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg",
    height: "71 - 86",
    weight: "71 - 86",
    lifeSpan: "10 - 12 years",
    temperaments: ["Loyal", "Independent", "Intelligent", "Brave"],
    breedGroup: "Working",
    id: 5,
  },
  {
    name: "Akita",
    img: "https://cdn2.thedogapi.com/images/BFRYBufpm.jpg",
    height: "61 - 71",
    weight: "61 - 71",
    lifeSpan: "10 - 14 years",
    temperaments: [
      "Docile",
      "Alert",
      "Responsive",
      "Dignified",
      "Composed",
      "Friendly",
      "Receptive",
      "Faithful",
      "Courageous",
    ],
    breedGroup: "Working",
    id: 6,
  },
  {
    name: "Alapaha Blue Blood Bulldog",
    img: "https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg",
    height: "46 - 61",
    weight: "46 - 61",
    lifeSpan: "12 - 13 years",
    temperaments: [
      "Loving",
      "Protective",
      "Trainable",
      "Dutiful",
      "Responsible",
    ],
    breedGroup: "Mixed",
    id: 7,
  },
  {
    name: "Alaskan Husky",
    img: "https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg",
    height: "58 - 66",
    weight: "58 - 66",
    lifeSpan: "10 - 13 years",
    temperaments: ["Friendly", "Energetic", "Loyal", "Gentle", "Confident"],
    breedGroup: "Mixed",
    id: 8,
  },
  {
    name: "Alaskan Malamute",
    img: "https://cdn2.thedogapi.com/images/dW5UucTIW.jpg",
    height: "58 - 64",
    weight: "58 - 64",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Friendly",
      "Affectionate",
      "Devoted",
      "Loyal",
      "Dignified",
      "Playful",
    ],
    breedGroup: "Working",
    id: 9,
  },
  {
    name: "American Bulldog",
    img: "https://cdn2.thedogapi.com/images/pk1AAdloG.jpg",
    height: "56 - 69",
    weight: "56 - 69",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Friendly",
      "Assertive",
      "Energetic",
      "Loyal",
      "Gentle",
      "Confident",
      "Dominant",
    ],
    breedGroup: "Working",
    id: 10,
  },
  {
    name: "American Bully",
    img: "https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg",
    height: "36 - 43",
    weight: "36 - 43",
    lifeSpan: "8 - 15 years",
    temperaments: [
      "Strong Willed",
      "Stubborn",
      "Friendly",
      "Clownish",
      "Affectionate",
      "Loyal",
      "Obedient",
      "Intelligent",
      "Courageous",
    ],
    breedGroup: "Unknown",
    id: 11,
  },
  {
    name: "American Eskimo Dog",
    img: "https://cdn2.thedogapi.com/images/Bymjyec4m.jpg",
    height: "38 - 48",
    weight: "38 - 48",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Friendly",
      "Alert",
      "Reserved",
      "Intelligent",
      "Protective",
    ],
    breedGroup: "Non-Sporting",
    id: 12,
  },
  {
    name: "American Eskimo Dog (Miniature)",
    img: "https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg",
    height: "23 - 30",
    weight: "23 - 30",
    lifeSpan: "13 - 15 years",
    temperaments: [
      "Friendly",
      "Alert",
      "Reserved",
      "Intelligent",
      "Protective",
    ],
    breedGroup: "Unknown",
    id: 13,
  },
  {
    name: "American Foxhound",
    img: "https://cdn2.thedogapi.com/images/S14n1x9NQ.jpg",
    height: "53 - 71",
    weight: "53 - 71",
    lifeSpan: "8 - 15 years",
    temperaments: [
      "Kind",
      "Sweet-Tempered",
      "Loyal",
      "Independent",
      "Intelligent",
      "Loving",
    ],
    breedGroup: "Hound",
    id: 14,
  },
  {
    name: "American Pit Bull Terrier",
    img: "https://cdn2.thedogapi.com/images/HkC31gcNm.png",
    height: "43 - 53",
    weight: "43 - 53",
    lifeSpan: "10 - 15 years",
    temperaments: [
      "Strong Willed",
      "Stubborn",
      "Friendly",
      "Clownish",
      "Affectionate",
      "Loyal",
      "Obedient",
      "Intelligent",
      "Courageous",
    ],
    breedGroup: "Terrier",
    id: 15,
  },
  {
    name: "American Staffordshire Terrier",
    img: "https://cdn2.thedogapi.com/images/rJIakgc4m.jpg",
    height: "43 - 48",
    weight: "43 - 48",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Tenacious",
      "Friendly",
      "Devoted",
      "Loyal",
      "Attentive",
      "Courageous",
    ],
    breedGroup: "Terrier",
    id: 16,
  },
  {
    name: "American Water Spaniel",
    img: "https://cdn2.thedogapi.com/images/SkmRJl9VQ.jpg",
    height: "38 - 46",
    weight: "38 - 46",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Friendly",
      "Energetic",
      "Obedient",
      "Intelligent",
      "Protective",
      "Trainable",
    ],
    breedGroup: "Sporting",
    id: 17,
  },
  {
    name: "Anatolian Shepherd Dog",
    img: "https://cdn2.thedogapi.com/images/BJT0Jx5Nm.jpg",
    height: "69 - 74",
    weight: "69 - 74",
    lifeSpan: "11 - 13 years",
    temperaments: [
      "Steady",
      "Bold",
      "Independent",
      "Confident",
      "Intelligent",
      "Proud",
    ],
    breedGroup: "Working",
    id: 18,
  },
  {
    name: "Appenzeller Sennenhund",
    img: "https://cdn2.thedogapi.com/images/HkNkxlqEX.jpg",
    height: "51 - 56",
    weight: "51 - 56",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Reliable",
      "Fearless",
      "Energetic",
      "Lively",
      "Self-assured",
    ],
    breedGroup: "Unknown",
    id: 19,
  },
  {
    name: "Australian Cattle Dog",
    img: "https://cdn2.thedogapi.com/images/IBkYVm4v1.jpg",
    height: "43 - 51",
    weight: "43 - 51",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Cautious",
      "Energetic",
      "Loyal",
      "Obedient",
      "Protective",
      "Brave",
    ],
    breedGroup: "Herding",
    id: 20,
  },
  {
    name: "Australian Kelpie",
    img: "https://cdn2.thedogapi.com/images/Hyq1ge9VQ.jpg",
    height: "43 - 51",
    weight: "43 - 51",
    lifeSpan: "10 - 13 years",
    temperaments: [
      "Friendly",
      "Energetic",
      "Alert",
      "Loyal",
      "Intelligent",
      "Eager",
    ],
    breedGroup: "Herding",
    id: 21,
  },
  {
    name: "Australian Shepherd",
    img: "https://cdn2.thedogapi.com/images/B1-llgq4m.jpg",
    height: "46 - 58",
    weight: "46 - 58",
    lifeSpan: "12 - 16 years",
    temperaments: [
      "Good-natured",
      "Affectionate",
      "Intelligent",
      "Active",
      "Protective",
    ],
    breedGroup: "Herding",
    id: 22,
  },
  {
    name: "Australian Terrier",
    img: "https://cdn2.thedogapi.com/images/r1Ylge5Vm.jpg",
    height: "25 - 28",
    weight: "25 - 28",
    lifeSpan: "15 years",
    temperaments: [
      "Spirited",
      "Alert",
      "Loyal",
      "Companionable",
      "Even Tempered",
      "Courageous",
    ],
    breedGroup: "Terrier",
    id: 23,
  },
  {
    name: "Azawakh",
    img: "https://cdn2.thedogapi.com/images/SkvZgx94m.jpg",
    height: "58 - 74",
    weight: "58 - 74",
    lifeSpan: "10 - 13 years",
    temperaments: [
      "Aloof",
      "Affectionate",
      "Attentive",
      "Rugged",
      "Fierce",
      "Refined",
    ],
    breedGroup: "Hound",
    id: 24,
  },
  {
    name: "Barbet",
    img: "https://cdn2.thedogapi.com/images/HyWGexcVQ.jpg",
    height: "51 - 66",
    weight: "51 - 66",
    lifeSpan: "13 - 15 years",
    temperaments: ["Obedient", "Companionable", "Intelligent", "Joyful"],
    breedGroup: "Unknown",
    id: 25,
  },
  {
    name: "Basenji",
    img: "https://cdn2.thedogapi.com/images/H1dGlxqNQ.jpg",
    height: "41 - 43",
    weight: "41 - 43",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Affectionate",
      "Energetic",
      "Alert",
      "Curious",
      "Playful",
      "Intelligent",
    ],
    breedGroup: "Hound",
    id: 26,
  },
  {
    name: "Basset Bleu de Gascogne",
    img: "https://cdn2.thedogapi.com/images/BkMQll94X.jpg",
    height: "33 - 38",
    weight: "33 - 38",
    lifeSpan: "10 - 14 years",
    temperaments: [
      "Affectionate",
      "Lively",
      "Agile",
      "Curious",
      "Happy",
      "Active",
    ],
    breedGroup: "Hound",
    id: 27,
  },
  {
    name: "Basset Hound",
    img: "https://cdn2.thedogapi.com/images/Sy57xx9EX.jpg",
    height: "36",
    weight: "36",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Tenacious",
      "Friendly",
      "Affectionate",
      "Devoted",
      "Sweet-Tempered",
      "Gentle",
    ],
    breedGroup: "Hound",
    id: 28,
  },
  {
    name: "Beagle",
    img: "https://cdn2.thedogapi.com/images/Syd4xxqEm.jpg",
    height: "33 - 38",
    weight: "33 - 38",
    lifeSpan: "13 - 16 years",
    temperaments: [
      "Amiable",
      "Even Tempered",
      "Excitable",
      "Determined",
      "Gentle",
      "Intelligent",
    ],
    breedGroup: "Hound",
    id: 29,
  },
  {
    name: "Bearded Collie",
    img: "https://cdn2.thedogapi.com/images/A09F4c1qP.jpg",
    height: "51 - 56",
    weight: "51 - 56",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Self-confidence",
      "Hardy",
      "Lively",
      "Alert",
      "Intelligent",
      "Active",
    ],
    breedGroup: "Herding",
    id: 30,
  },
  {
    name: "Beauceron",
    img: "https://cdn2.thedogapi.com/images/HJQ8ge5V7.jpg",
    height: "61 - 70",
    weight: "61 - 70",
    lifeSpan: "10 - 12 years",
    temperaments: ["Fearless", "Friendly", "Intelligent", "Protective", "Calm"],
    breedGroup: "Herding",
    id: 31,
  },
  {
    name: "Bedlington Terrier",
    img: "https://cdn2.thedogapi.com/images/ByK8gx947.jpg",
    height: "38 - 41",
    weight: "38 - 41",
    lifeSpan: "14 - 16 years",
    temperaments: ["Affectionate", "Spirited", "Intelligent", "Good-tempered"],
    breedGroup: "Terrier",
    id: 32,
  },
  {
    name: "Belgian Malinois",
    img: "https://cdn2.thedogapi.com/images/r1f_ll5VX.jpg",
    height: "56 - 66",
    weight: "56 - 66",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Watchful",
      "Alert",
      "Stubborn",
      "Friendly",
      "Confident",
      "Hard-working",
      "Active",
      "Protective",
    ],
    breedGroup: "Herding",
    id: 33,
  },
  {
    name: "Belgian Tervuren",
    img: "https://cdn2.thedogapi.com/images/B1KdxlcNX.jpg",
    height: "56 - 66",
    weight: "56 - 66",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Energetic",
      "Alert",
      "Loyal",
      "Intelligent",
      "Attentive",
      "Protective",
    ],
    breedGroup: "Herding",
    id: 34,
  },
  {
    name: "Bernese Mountain Dog",
    img: "https://cdn2.thedogapi.com/images/S1fFlx5Em.jpg",
    height: "58 - 70",
    weight: "58 - 70",
    lifeSpan: "7 - 10 years",
    temperaments: ["Affectionate", "Loyal", "Intelligent", "Faithful"],
    breedGroup: "Working",
    id: 35,
  },
  {
    name: "Bichon Frise",
    img: "https://cdn2.thedogapi.com/images/HkuYlxqEQ.jpg",
    height: "24 - 29",
    weight: "24 - 29",
    lifeSpan: "15 years",
    temperaments: [
      "Feisty",
      "Affectionate",
      "Cheerful",
      "Playful",
      "Gentle",
      "Sensitive",
    ],
    breedGroup: "Non-Sporting",
    id: 36,
  },
  {
    name: "Black and Tan Coonhound",
    img: "https://cdn2.thedogapi.com/images/HJAFgxcNQ.jpg",
    height: "58 - 69",
    weight: "58 - 69",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Easygoing",
      "Gentle",
      "Adaptable",
      "Trusting",
      "Even Tempered",
      "Lovable",
    ],
    breedGroup: "Hound",
    id: 37,
  },
  {
    name: "Bloodhound",
    img: "https://cdn2.thedogapi.com/images/Skdcgx9VX.jpg",
    height: "58 - 69",
    weight: "58 - 69",
    lifeSpan: "8 - 10 years",
    temperaments: ["Stubborn", "Affectionate", "Gentle", "Even Tempered"],
    breedGroup: "Hound",
    id: 38,
  },
  {
    name: "Bluetick Coonhound",
    img: "https://cdn2.thedogapi.com/images/rJxieg9VQ.jpg",
    height: "53 - 69",
    weight: "53 - 69",
    lifeSpan: "12 - 14 years",
    temperaments: ["Friendly", "Intelligent", "Active"],
    breedGroup: "Hound",
    id: 39,
  },
  {
    name: "Boerboel",
    img: "https://cdn2.thedogapi.com/images/HyOjge5Vm.jpg",
    height: "56 - 69",
    weight: "56 - 69",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Obedient",
      "Confident",
      "Intelligent",
      "Dominant",
      "Territorial",
    ],
    breedGroup: "Working",
    id: 40,
  },
  {
    name: "Border Collie",
    img: "https://cdn2.thedogapi.com/images/sGQvQUpsp.jpg",
    height: "46 - 56",
    weight: "46 - 56",
    lifeSpan: "12 - 16 years",
    temperaments: [
      "Tenacious",
      "Keen",
      "Energetic",
      "Responsive",
      "Alert",
      "Intelligent",
    ],
    breedGroup: "Herding",
    id: 41,
  },
  {
    name: "Border Terrier",
    img: "https://cdn2.thedogapi.com/images/HJOpge9Em.jpg",
    height: "28 - 41",
    weight: "28 - 41",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Fearless",
      "Affectionate",
      "Alert",
      "Obedient",
      "Intelligent",
      "Even Tempered",
    ],
    breedGroup: "Terrier",
    id: 42,
  },
  {
    name: "Boston Terrier",
    img: "https://cdn2.thedogapi.com/images/rkZRggqVX.jpg",
    height: "41 - 43",
    weight: "41 - 43",
    lifeSpan: "11 - 13 years",
    temperaments: ["Friendly", "Lively", "Intelligent"],
    breedGroup: "Non-Sporting",
    id: 43,
  },
  {
    name: "Bouvier des Flandres",
    img: "https://cdn2.thedogapi.com/images/Byd0xl5VX.jpg",
    height: "60 - 70",
    weight: "60 - 70",
    lifeSpan: "10 - 15 years",
    temperaments: [
      "Protective",
      "Loyal",
      "Gentle",
      "Intelligent",
      "Familial",
      "Rational",
    ],
    breedGroup: "Herding",
    id: 44,
  },
  {
    name: "Boxer",
    img: "https://cdn2.thedogapi.com/images/ry1kWe5VQ.jpg",
    height: "55 - 64",
    weight: "55 - 64",
    lifeSpan: "8 - 10 years",
    temperaments: [
      "Devoted",
      "Fearless",
      "Friendly",
      "Cheerful",
      "Energetic",
      "Loyal",
      "Playful",
      "Confident",
      "Intelligent",
      "Bright",
      "Brave",
      "Calm",
    ],
    breedGroup: "Working",
    id: 45,
  },
  {
    name: "Boykin Spaniel",
    img: "https://cdn2.thedogapi.com/images/ryHJZlcNX.jpg",
    height: "36 - 46",
    weight: "36 - 46",
    lifeSpan: "10 - 14 years",
    temperaments: [
      "Friendly",
      "Energetic",
      "Companionable",
      "Intelligent",
      "Eager",
      "Trainable",
    ],
    breedGroup: "Sporting",
    id: 46,
  },
  {
    name: "Bracco Italiano",
    img: "https://cdn2.thedogapi.com/images/S13yZg5VQ.jpg",
    height: "55 - 67",
    weight: "55 - 67",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Stubborn",
      "Affectionate",
      "Loyal",
      "Playful",
      "Companionable",
      "Trainable",
    ],
    breedGroup: "Sporting",
    id: 47,
  },
  {
    name: "Briard",
    img: "https://cdn2.thedogapi.com/images/rkVlblcEQ.jpg",
    height: "56 - 69",
    weight: "56 - 69",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Fearless",
      "Loyal",
      "Obedient",
      "Intelligent",
      "Faithful",
      "Protective",
    ],
    breedGroup: "Herding",
    id: 48,
  },
  {
    name: "Brittany",
    img: "https://cdn2.thedogapi.com/images/HJWZZxc4X.jpg",
    height: "44 - 52",
    weight: "44 - 52",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Agile",
      "Adaptable",
      "Quick",
      "Intelligent",
      "Attentive",
      "Happy",
    ],
    breedGroup: "Sporting",
    id: 49,
  },
  {
    name: "Bull Terrier",
    img: "https://cdn2.thedogapi.com/images/VSraIEQGd.jpg",
    height: "53 - 56",
    weight: "53 - 56",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Trainable",
      "Protective",
      "Sweet-Tempered",
      "Keen",
      "Active",
    ],
    breedGroup: "Terrier",
    id: 50,
  },
  {
    name: "Bull Terrier (Miniature)",
    img: "https://cdn2.thedogapi.com/images/BkKZWlcVX.jpg",
    height: "25 - 36",
    weight: "25 - 36",
    lifeSpan: "11 - 14 years",
    temperaments: [
      "Trainable",
      "Protective",
      "Sweet-Tempered",
      "Keen",
      "Active",
      "Territorial",
    ],
    breedGroup: "Unknown",
    id: 51,
  },
  {
    name: "Bullmastiff",
    img: "https://cdn2.thedogapi.com/images/r1ifZl5E7.jpg",
    height: "61 - 69",
    weight: "61 - 69",
    lifeSpan: "8 - 12 years",
    temperaments: [
      "Docile",
      "Reliable",
      "Devoted",
      "Alert",
      "Loyal",
      "Reserved",
      "Loving",
      "Protective",
      "Powerful",
      "Calm",
      "Courageous",
    ],
    breedGroup: "Working",
    id: 52,
  },
  {
    name: "Cairn Terrier",
    img: "https://cdn2.thedogapi.com/images/Sk7Qbg9E7.jpg",
    height: "23 - 25",
    weight: "23 - 25",
    lifeSpan: "14 - 15 years",
    temperaments: [
      "Hardy",
      "Fearless",
      "Assertive",
      "Gay",
      "Intelligent",
      "Active",
    ],
    breedGroup: "Terrier",
    id: 53,
  },
  {
    name: "Cane Corso",
    img: "https://cdn2.thedogapi.com/images/r15m-lc4m.jpg",
    height: "60 - 70",
    weight: "60 - 70",
    lifeSpan: "10 - 11 years",
    temperaments: [
      "Trainable",
      "Reserved",
      "Stable",
      "Quiet",
      "Even Tempered",
      "Calm",
    ],
    breedGroup: "Working",
    id: 54,
  },
  {
    name: "Cardigan Welsh Corgi",
    img: "https://cdn2.thedogapi.com/images/SyXN-e9NX.jpg",
    height: "27 - 32",
    weight: "27 - 32",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Affectionate",
      "Devoted",
      "Alert",
      "Companionable",
      "Intelligent",
      "Active",
    ],
    breedGroup: "Herding",
    id: 55,
  },
  {
    name: "Catahoula Leopard Dog",
    img: "https://cdn2.thedogapi.com/images/BJcNbec4X.jpg",
    height: "51 - 66",
    weight: "51 - 66",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Energetic",
      "Inquisitive",
      "Independent",
      "Gentle",
      "Intelligent",
      "Loving",
    ],
    breedGroup: "Herding",
    id: 56,
  },
  {
    name: "Caucasian Shepherd (Ovcharka)",
    img: "https://cdn2.thedogapi.com/images/r1rrWe5Em.jpg",
    height: "61 - 85",
    weight: "61 - 85",
    lifeSpan: "10 - 12 years",
    temperaments: ["Alert", "Quick", "Dominant", "Powerful", "Calm", "Strong"],
    breedGroup: "Working",
    id: 57,
  },
  {
    name: "Cavalier King Charles Spaniel",
    img: "https://cdn2.thedogapi.com/images/HJRBbe94Q.jpg",
    height: "30 - 33",
    weight: "30 - 33",
    lifeSpan: "10 - 14 years",
    temperaments: [
      "Fearless",
      "Affectionate",
      "Sociable",
      "Patient",
      "Playful",
      "Adaptable",
    ],
    breedGroup: "Toy",
    id: 58,
  },
  {
    name: "Chesapeake Bay Retriever",
    img: "https://cdn2.thedogapi.com/images/9BXwUeCc2.jpg",
    height: "53 - 66",
    weight: "53 - 66",
    lifeSpan: "10 - 13 years",
    temperaments: [
      "Affectionate",
      "Intelligent",
      "Quiet",
      "Dominant",
      "Happy",
      "Protective",
    ],
    breedGroup: "Sporting",
    id: 59,
  },
  {
    name: "Chinese Crested",
    img: "https://cdn2.thedogapi.com/images/B1pDZx9Nm.jpg",
    height: "28 - 33",
    weight: "28 - 33",
    lifeSpan: "10 - 14 years",
    temperaments: [
      "Affectionate",
      "Sweet-Tempered",
      "Lively",
      "Alert",
      "Playful",
      "Happy",
    ],
    breedGroup: "Toy",
    id: 60,
  },
  {
    name: "Chinese Shar-Pei",
    img: "https://cdn2.thedogapi.com/images/B1ruWl94Q.jpg",
    height: "46 - 51",
    weight: "46 - 51",
    lifeSpan: "10 years",
    temperaments: [
      "Suspicious",
      "Affectionate",
      "Devoted",
      "Reserved",
      "Independent",
      "Loving",
    ],
    breedGroup: "Non-Sporting",
    id: 61,
  },
  {
    name: "Chinook",
    img: "https://cdn2.thedogapi.com/images/Sypubg54Q.jpg",
    height: "56 - 66",
    weight: "56 - 66",
    lifeSpan: "12 - 15 years",
    temperaments: ["Friendly", "Alert", "Dignified", "Intelligent", "Calm"],
    breedGroup: "Working",
    id: 62,
  },
  {
    name: "Chow Chow",
    img: "https://cdn2.thedogapi.com/images/ry8KWgqEQ.jpg",
    height: "43 - 51",
    weight: "43 - 51",
    lifeSpan: "12 - 15 years",
    temperaments: ["Aloof", "Loyal", "Independent", "Quiet"],
    breedGroup: "Non-Sporting",
    id: 63,
  },
  {
    name: "Clumber Spaniel",
    img: "https://cdn2.thedogapi.com/images/rkeqWgq4Q.jpg",
    height: "43 - 51",
    weight: "43 - 51",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Affectionate",
      "Loyal",
      "Dignified",
      "Gentle",
      "Calm",
      "Great-hearted",
    ],
    breedGroup: "Sporting",
    id: 64,
  },
  {
    name: "Cocker Spaniel",
    img: "https://cdn2.thedogapi.com/images/1lFmrzECl.jpg",
    height: "36 - 38",
    weight: "36 - 38",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Trainable",
      "Friendly",
      "Affectionate",
      "Playful",
      "Quiet",
      "Faithful",
    ],
    breedGroup: "Sporting",
    id: 65,
  },
  {
    name: "Cocker Spaniel (American)",
    img: "https://cdn2.thedogapi.com/images/HkRcZe547.jpg",
    height: "36 - 38",
    weight: "36 - 38",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Outgoing",
      "Sociable",
      "Trusting",
      "Joyful",
      "Even Tempered",
      "Merry",
    ],
    breedGroup: "Sporting",
    id: 66,
  },
  {
    name: "Coton de Tulear",
    img: "https://cdn2.thedogapi.com/images/SyviZlqNm.jpg",
    height: "23 - 28",
    weight: "23 - 28",
    lifeSpan: "13 - 16 years",
    temperaments: [
      "Affectionate",
      "Lively",
      "Playful",
      "Intelligent",
      "Trainable",
      "Vocal",
    ],
    breedGroup: "Non-Sporting",
    id: 67,
  },
  {
    name: "Dalmatian",
    img: "https://cdn2.thedogapi.com/images/SkJ3blcN7.jpg",
    height: "48 - 58",
    weight: "48 - 58",
    lifeSpan: "10 - 13 years",
    temperaments: [
      "Outgoing",
      "Friendly",
      "Energetic",
      "Playful",
      "Sensitive",
      "Intelligent",
      "Active",
    ],
    breedGroup: "Non-Sporting",
    id: 68,
  },
  {
    name: "Doberman Pinscher",
    img: "https://cdn2.thedogapi.com/images/HyL3bl94Q.jpg",
    height: "61 - 71",
    weight: "61 - 71",
    lifeSpan: "10 years",
    temperaments: [
      "Fearless",
      "Energetic",
      "Alert",
      "Loyal",
      "Obedient",
      "Confident",
      "Intelligent",
    ],
    breedGroup: "Working",
    id: 69,
  },
  {
    name: "Dogo Argentino",
    img: "https://cdn2.thedogapi.com/images/S1nhWx94Q.jpg",
    height: "60 - 69",
    weight: "60 - 69",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Friendly",
      "Affectionate",
      "Cheerful",
      "Loyal",
      "Tolerant",
      "Protective",
    ],
    breedGroup: "Working",
    id: 70,
  },
  {
    name: "Dutch Shepherd",
    img: "https://cdn2.thedogapi.com/images/BkE6Wg5E7.jpg",
    height: "56 - 62",
    weight: "56 - 62",
    lifeSpan: "15 years",
    temperaments: [
      "Reliable",
      "Affectionate",
      "Alert",
      "Loyal",
      "Obedient",
      "Trainable",
    ],
    breedGroup: "Unknown",
    id: 71,
  },
  {
    name: "English Setter",
    img: "https://cdn2.thedogapi.com/images/By4A-eqVX.jpg",
    height: "61 - 64",
    weight: "61 - 64",
    lifeSpan: "12 years",
    temperaments: [
      "Strong Willed",
      "Mischievous",
      "Affectionate",
      "Energetic",
      "Playful",
      "Companionable",
      "Gentle",
      "Hard-working",
      "Intelligent",
      "Eager",
      "People-Oriented",
    ],
    breedGroup: "Sporting",
    id: 72,
  },
  {
    name: "English Shepherd",
    img: "https://cdn2.thedogapi.com/images/H1QyMe5EQ.jpg",
    height: "46 - 58",
    weight: "46 - 58",
    lifeSpan: "10 - 13 years",
    temperaments: [
      "Kind",
      "Energetic",
      "Independent",
      "Adaptable",
      "Intelligent",
      "Bossy",
    ],
    breedGroup: "Working",
    id: 73,
  },
  {
    name: "English Springer Spaniel",
    img: "https://cdn2.thedogapi.com/images/Hk0Jfe5VQ.jpg",
    height: "48 - 51",
    weight: "48 - 51",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Affectionate",
      "Cheerful",
      "Alert",
      "Intelligent",
      "Attentive",
      "Active",
    ],
    breedGroup: "Sporting",
    id: 74,
  },
  {
    name: "English Toy Spaniel",
    img: "https://cdn2.thedogapi.com/images/SkIgzxqNQ.jpg",
    height: "25",
    weight: "25",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Affectionate",
      "Reserved",
      "Playful",
      "Gentle",
      "Happy",
      "Loving",
    ],
    breedGroup: "Toy",
    id: 75,
  },
  {
    name: "English Toy Terrier",
    img: "https://cdn2.thedogapi.com/images/SJ6eMxqEQ.jpg",
    height: "25 - 30",
    weight: "25 - 30",
    lifeSpan: "12 - 13 years",
    temperaments: [
      "Stubborn",
      "Alert",
      "Companionable",
      "Intelligent",
      "Cunning",
      "Trainable",
    ],
    breedGroup: "Unknown",
    id: 76,
  },
  {
    name: "Eurasier",
    img: "https://cdn2.thedogapi.com/images/S1VWGx9Nm.jpg",
    height: "52 - 60",
    weight: "52 - 60",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Alert",
      "Reserved",
      "Intelligent",
      "Even Tempered",
      "Watchful",
      "Calm",
    ],
    breedGroup: "Non-Sporting",
    id: 77,
  },
  {
    name: "Field Spaniel",
    img: "https://cdn2.thedogapi.com/images/SkJfGecE7.jpg",
    height: "43 - 46",
    weight: "43 - 46",
    lifeSpan: "11 - 15 years",
    temperaments: [
      "Docile",
      "Cautious",
      "Sociable",
      "Sensitive",
      "Adaptable",
      "Familial",
    ],
    breedGroup: "Sporting",
    id: 78,
  },
  {
    name: "Finnish Lapphund",
    img: "https://cdn2.thedogapi.com/images/S1KMGg5Vm.jpg",
    height: "41 - 53",
    weight: "41 - 53",
    lifeSpan: "12 - 15 years",
    temperaments: ["Friendly", "Keen", "Faithful", "Calm", "Courageous"],
    breedGroup: "Herding",
    id: 79,
  },
  {
    name: "Finnish Spitz",
    img: "https://cdn2.thedogapi.com/images/3PjHlQbkV.jpg",
    height: "39 - 51",
    weight: "39 - 51",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Playful",
      "Loyal",
      "Independent",
      "Intelligent",
      "Happy",
      "Vocal",
    ],
    breedGroup: "Non-Sporting",
    id: 80,
  },
  {
    name: "French Bulldog",
    img: "https://cdn2.thedogapi.com/images/HyWNfxc47.jpg",
    height: "28 - 30",
    weight: "28 - 30",
    lifeSpan: "9 - 11 years",
    temperaments: [
      "Playful",
      "Affectionate",
      "Keen",
      "Sociable",
      "Lively",
      "Alert",
      "Easygoing",
      "Patient",
      "Athletic",
      "Bright",
    ],
    breedGroup: "Non-Sporting",
    id: 81,
  },
  {
    name: "German Pinscher",
    img: "https://cdn2.thedogapi.com/images/B1u4zgqE7.jpg",
    height: "43 - 51",
    weight: "43 - 51",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Spirited",
      "Lively",
      "Intelligent",
      "Loving",
      "Even Tempered",
      "Familial",
    ],
    breedGroup: "Working",
    id: 82,
  },
  {
    name: "German Shepherd Dog",
    img: "https://cdn2.thedogapi.com/images/SJyBfg5NX.jpg",
    height: "56 - 66",
    weight: "56 - 66",
    lifeSpan: "10 - 13 years",
    temperaments: [
      "Alert",
      "Loyal",
      "Obedient",
      "Curious",
      "Confident",
      "Intelligent",
      "Watchful",
      "Courageous",
    ],
    breedGroup: "Herding",
    id: 83,
  },
  {
    name: "German Shorthaired Pointer",
    img: "https://cdn2.thedogapi.com/images/SJqBMg5Nm.jpg",
    height: "53 - 64",
    weight: "53 - 64",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Boisterous",
      "Bold",
      "Affectionate",
      "Intelligent",
      "Cooperative",
      "Trainable",
    ],
    breedGroup: "Sporting",
    id: 84,
  },
  {
    name: "Giant Schnauzer",
    img: "https://cdn2.thedogapi.com/images/H1NIzlcV7.jpg",
    height: "60 - 70",
    weight: "60 - 70",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Strong Willed",
      "Kind",
      "Loyal",
      "Intelligent",
      "Dominant",
      "Powerful",
    ],
    breedGroup: "Working",
    id: 85,
  },
  {
    name: "Glen of Imaal Terrier",
    img: "https://cdn2.thedogapi.com/images/H1oLMe94m.jpg",
    height: "32 - 36",
    weight: "32 - 36",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Spirited",
      "Agile",
      "Loyal",
      "Gentle",
      "Active",
      "Courageous",
    ],
    breedGroup: "Terrier",
    id: 86,
  },
  {
    name: "Golden Retriever",
    img: "https://cdn2.thedogapi.com/images/HJ7Pzg5EQ.jpg",
    height: "55 - 61",
    weight: "55 - 61",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Intelligent",
      "Kind",
      "Reliable",
      "Friendly",
      "Trustworthy",
      "Confident",
    ],
    breedGroup: "Sporting",
    id: 87,
  },
  {
    name: "Gordon Setter",
    img: "https://cdn2.thedogapi.com/images/SJ5vzx5NX.jpg",
    height: "58 - 69",
    weight: "58 - 69",
    lifeSpan: "10 - 12 years",
    temperaments: ["Fearless", "Alert", "Loyal", "Confident", "Gay", "Eager"],
    breedGroup: "Sporting",
    id: 88,
  },
  {
    name: "Great Dane",
    img: "https://cdn2.thedogapi.com/images/B1Edfl9NX.jpg",
    height: "71 - 81",
    weight: "71 - 81",
    lifeSpan: "7 - 10 years",
    temperaments: [
      "Friendly",
      "Devoted",
      "Reserved",
      "Gentle",
      "Confident",
      "Loving",
    ],
    breedGroup: "Working",
    id: 89,
  },
  {
    name: "Great Pyrenees",
    img: "https://cdn2.thedogapi.com/images/B12uzg9V7.png",
    height: "64 - 81",
    weight: "64 - 81",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Strong Willed",
      "Fearless",
      "Affectionate",
      "Patient",
      "Gentle",
      "Confident",
    ],
    breedGroup: "Working",
    id: 90,
  },
  {
    name: "Greyhound",
    img: "https://cdn2.thedogapi.com/images/ryNYMx94X.jpg",
    height: "69 - 76",
    weight: "69 - 76",
    lifeSpan: "10 - 13 years",
    temperaments: [
      "Affectionate",
      "Athletic",
      "Gentle",
      "Intelligent",
      "Quiet",
      "Even Tempered",
    ],
    breedGroup: "Hound",
    id: 91,
  },
  {
    name: "Griffon Bruxellois",
    img: "https://cdn2.thedogapi.com/images/ryoYGec4Q.jpg",
    height: "23 - 28",
    weight: "23 - 28",
    lifeSpan: "10 - 15 years",
    temperaments: [
      "Self-important",
      "Inquisitive",
      "Alert",
      "Companionable",
      "Sensitive",
      "Watchful",
    ],
    breedGroup: "Unknown",
    id: 92,
  },
  {
    name: "Harrier",
    img: "https://cdn2.thedogapi.com/images/B1IcfgqE7.jpg",
    height: "46 - 56",
    weight: "46 - 56",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Outgoing",
      "Friendly",
      "Cheerful",
      "Sweet-Tempered",
      "Tolerant",
      "Active",
    ],
    breedGroup: "Hound",
    id: 93,
  },
  {
    name: "Havanese",
    img: "https://cdn2.thedogapi.com/images/rkXiGl9V7.jpg",
    height: "22 - 29",
    weight: "22 - 29",
    lifeSpan: "14 - 15 years",
    temperaments: [
      "Affectionate",
      "Responsive",
      "Playful",
      "Companionable",
      "Gentle",
      "Intelligent",
    ],
    breedGroup: "Toy",
    id: 94,
  },
  {
    name: "Irish Setter",
    img: "https://cdn2.thedogapi.com/images/S1osGeqVm.jpg",
    height: "61 - 69",
    weight: "61 - 69",
    lifeSpan: "10 - 11 years",
    temperaments: [
      "Affectionate",
      "Energetic",
      "Lively",
      "Independent",
      "Playful",
      "Companionable",
    ],
    breedGroup: "Sporting",
    id: 95,
  },
  {
    name: "Irish Terrier",
    img: "https://cdn2.thedogapi.com/images/By-hGecVX.jpg",
    height: "46",
    weight: "46",
    lifeSpan: "12 - 16 years",
    temperaments: [
      "Respectful",
      "Lively",
      "Intelligent",
      "Dominant",
      "Protective",
      "Trainable",
    ],
    breedGroup: "Terrier",
    id: 96,
  },
  {
    name: "Irish Wolfhound",
    img: "https://cdn2.thedogapi.com/images/Hyd2zgcEX.jpg",
    height: "76 - 89",
    weight: "76 - 89",
    lifeSpan: "6 - 8 years",
    temperaments: [
      "Sweet-Tempered",
      "Loyal",
      "Dignified",
      "Patient",
      "Thoughtful",
      "Generous",
    ],
    breedGroup: "Hound",
    id: 97,
  },
  {
    name: "Italian Greyhound",
    img: "https://cdn2.thedogapi.com/images/SJAnzg9NX.jpg",
    height: "33 - 38",
    weight: "33 - 38",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Mischievous",
      "Affectionate",
      "Agile",
      "Athletic",
      "Companionable",
      "Intelligent",
    ],
    breedGroup: "Toy",
    id: 98,
  },
  {
    name: "Japanese Chin",
    img: "https://cdn2.thedogapi.com/images/r1H6feqEm.jpg",
    height: "20 - 28",
    weight: "20 - 28",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Alert",
      "Loyal",
      "Independent",
      "Intelligent",
      "Loving",
      "Cat-like",
    ],
    breedGroup: "Toy",
    id: 99,
  },
  {
    name: "Japanese Spitz",
    img: "https://cdn2.thedogapi.com/images/HksaMxqNX.jpg",
    height: "30 - 38",
    weight: "30 - 38",
    lifeSpan: "10 - 16 years",
    temperaments: [
      "Affectionate",
      "Obedient",
      "Playful",
      "Companionable",
      "Intelligent",
      "Proud",
    ],
    breedGroup: "Unknown",
    id: 100,
  },
  {
    name: "Keeshond",
    img: "https://cdn2.thedogapi.com/images/S1GAGg9Vm.jpg",
    height: "43 - 46",
    weight: "43 - 46",
    lifeSpan: "12 - 15 years",
    temperaments: ["Agile", "Obedient", "Playful", "Quick", "Sturdy", "Bright"],
    breedGroup: "Non-Sporting",
    id: 101,
  },
  {
    name: "Komondor",
    img: "https://cdn2.thedogapi.com/images/Bko0fl547.jpg",
    height: "65 - 70",
    weight: "65 - 70",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Steady",
      "Fearless",
      "Affectionate",
      "Independent",
      "Gentle",
      "Calm",
    ],
    breedGroup: "Working",
    id: 102,
  },
  {
    name: "Kooikerhondje",
    img: "https://cdn2.thedogapi.com/images/kOMy84GQE.jpg",
    height: "36 - 41",
    weight: "36 - 41",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Benevolent",
      "Agile",
      "Alert",
      "Intelligent",
      "Active",
      "Territorial",
    ],
    breedGroup: "Sporting",
    id: 103,
  },
  {
    name: "Kuvasz",
    img: "https://cdn2.thedogapi.com/images/BykZ7ecVX.jpg",
    height: "66 - 76",
    weight: "66 - 76",
    lifeSpan: "8 - 10 years",
    temperaments: [
      "Clownish",
      "Loyal",
      "Patient",
      "Independent",
      "Intelligent",
      "Protective",
    ],
    breedGroup: "Working",
    id: 104,
  },
  {
    name: "Labrador Retriever",
    img: "https://cdn2.thedogapi.com/images/B1uW7l5VX.jpg",
    height: "55 - 62",
    weight: "55 - 62",
    lifeSpan: "10 - 13 years",
    temperaments: [
      "Kind",
      "Outgoing",
      "Agile",
      "Gentle",
      "Intelligent",
      "Trusting",
      "Even Tempered",
    ],
    breedGroup: "Sporting",
    id: 105,
  },
  {
    name: "Lagotto Romagnolo",
    img: "https://cdn2.thedogapi.com/images/ryzzmgqE7.jpg",
    height: "41 - 48",
    weight: "41 - 48",
    lifeSpan: "14 - 16 years",
    temperaments: [
      "Keen",
      "Loyal",
      "Companionable",
      "Loving",
      "Active",
      "Trainable",
    ],
    breedGroup: "Sporting",
    id: 106,
  },
  {
    name: "Lancashire Heeler",
    img: "https://cdn2.thedogapi.com/images/S1RGml5Em.jpg",
    height: "25 - 30",
    weight: "25 - 30",
    lifeSpan: "12 - 15 years",
    temperaments: ["Clever", "Friendly", "Alert", "Intelligent"],
    breedGroup: "Unknown",
    id: 107,
  },
  {
    name: "Leonberger",
    img: "https://cdn2.thedogapi.com/images/ByrmQlqVm.jpg",
    height: "65 - 80",
    weight: "65 - 80",
    lifeSpan: "6 - 8 years",
    temperaments: [
      "Obedient",
      "Fearless",
      "Loyal",
      "Companionable",
      "Adaptable",
      "Loving",
    ],
    breedGroup: "Working",
    id: 108,
  },
  {
    name: "Lhasa Apso",
    img: "https://cdn2.thedogapi.com/images/SJp7Qe5EX.jpg",
    height: "25 - 28",
    weight: "25 - 28",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Steady",
      "Fearless",
      "Friendly",
      "Devoted",
      "Assertive",
      "Spirited",
      "Energetic",
      "Lively",
      "Alert",
      "Obedient",
      "Playful",
      "Intelligent",
    ],
    breedGroup: "Non-Sporting",
    id: 109,
  },
  {
    name: "Maltese",
    img: "https://cdn2.thedogapi.com/images/B1SV7gqN7.jpg",
    height: "20 - 25",
    weight: "20 - 25",
    lifeSpan: "15 - 18 years",
    temperaments: [
      "Playful",
      "Docile",
      "Fearless",
      "Affectionate",
      "Sweet-Tempered",
      "Lively",
      "Responsive",
      "Easygoing",
      "Gentle",
      "Intelligent",
      "Active",
    ],
    breedGroup: "Toy",
    id: 110,
  },
  {
    name: "Miniature American Shepherd",
    img: "https://cdn2.thedogapi.com/images/BkHHQgcN7.jpg",
    height: "33 - 46",
    weight: "33 - 46",
    lifeSpan: "12 - 15 years",
    temperaments: ["Energetic", "Loyal", "Intelligent", "Trainable"],
    breedGroup: "Herding",
    id: 111,
  },
  {
    name: "Miniature Pinscher",
    img: "https://cdn2.thedogapi.com/images/Hy3H7g94X.jpg",
    height: "25 - 32",
    weight: "25 - 32",
    lifeSpan: "15 years",
    temperaments: [
      "Clever",
      "Outgoing",
      "Friendly",
      "Energetic",
      "Responsive",
      "Playful",
    ],
    breedGroup: "Toy",
    id: 112,
  },
  {
    name: "Miniature Schnauzer",
    img: "https://cdn2.thedogapi.com/images/SJIUQl9NX.jpg",
    height: "30 - 36",
    weight: "30 - 36",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Fearless",
      "Friendly",
      "Spirited",
      "Alert",
      "Obedient",
      "Intelligent",
    ],
    breedGroup: "Terrier",
    id: 113,
  },
  {
    name: "Newfoundland",
    img: "https://cdn2.thedogapi.com/images/Sk4DXl54m.jpg",
    height: "66 - 71",
    weight: "66 - 71",
    lifeSpan: "8 - 10 years",
    temperaments: ["Sweet-Tempered", "Gentle", "Trainable"],
    breedGroup: "Working",
    id: 114,
  },
  {
    name: "Norfolk Terrier",
    img: "https://cdn2.thedogapi.com/images/B1ADQg94X.jpg",
    height: "23 - 25",
    weight: "23 - 25",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Self-confidence",
      "Fearless",
      "Spirited",
      "Companionable",
      "Happy",
      "Lovable",
    ],
    breedGroup: "Terrier",
    id: 115,
  },
  {
    name: "Norwich Terrier",
    img: "https://cdn2.thedogapi.com/images/BkgKXlqE7.jpg",
    height: "25",
    weight: "25",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Hardy",
      "Affectionate",
      "Energetic",
      "Sensitive",
      "Intelligent",
    ],
    breedGroup: "Terrier",
    id: 116,
  },
  {
    name: "Nova Scotia Duck Tolling Retriever",
    img: "https://cdn2.thedogapi.com/images/SyYtQe5V7.jpg",
    height: "43 - 53",
    weight: "43 - 53",
    lifeSpan: "12 - 14 years",
    temperaments: ["Outgoing", "Alert", "Patient", "Intelligent", "Loving"],
    breedGroup: "Sporting",
    id: 117,
  },
  {
    name: "Old English Sheepdog",
    img: "https://cdn2.thedogapi.com/images/HkZ57lq4m.jpg",
    height: "53",
    weight: "53",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Sociable",
      "Bubbly",
      "Playful",
      "Adaptable",
      "Intelligent",
      "Loving",
    ],
    breedGroup: "Herding",
    id: 118,
  },
  {
    name: "Olde English Bulldogge",
    img: "https://cdn2.thedogapi.com/images/B1d5me547.jpg",
    height: "38 - 48",
    weight: "38 - 48",
    lifeSpan: "9 - 14 years",
    temperaments: [
      "Friendly",
      "Alert",
      "Confident",
      "Loving",
      "Courageous",
      "Strong",
    ],
    breedGroup: "Unknown",
    id: 119,
  },
  {
    name: "Papillon",
    img: "https://cdn2.thedogapi.com/images/SkJj7e547.jpg",
    height: "20 - 28",
    weight: "20 - 28",
    lifeSpan: "13 - 17 years",
    temperaments: [
      "Hardy",
      "Friendly",
      "Energetic",
      "Alert",
      "Intelligent",
      "Happy",
    ],
    breedGroup: "Toy",
    id: 120,
  },
  {
    name: "Pekingese",
    img: "https://cdn2.thedogapi.com/images/ByIiml9Nm.jpg",
    height: "15 - 23",
    weight: "15 - 23",
    lifeSpan: "14 - 18 years",
    temperaments: [
      "Opinionated",
      "Good-natured",
      "Stubborn",
      "Affectionate",
      "Aggressive",
      "Intelligent",
    ],
    breedGroup: "Toy",
    id: 121,
  },
  {
    name: "Pembroke Welsh Corgi",
    img: "https://cdn2.thedogapi.com/images/rJ6iQeqEm.jpg",
    height: "25 - 30",
    weight: "25 - 30",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Tenacious",
      "Outgoing",
      "Friendly",
      "Bold",
      "Playful",
      "Protective",
    ],
    breedGroup: "Herding",
    id: 122,
  },
  {
    name: "Perro de Presa Canario",
    img: "https://cdn2.thedogapi.com/images/S1V3Qeq4X.jpg",
    height: "56 - 65",
    weight: "56 - 65",
    lifeSpan: "10 - 12 years",
    temperaments: ["Strong Willed", "Suspicious", "Gentle", "Dominant", "Calm"],
    breedGroup: "Working",
    id: 123,
  },
  {
    name: "Pharaoh Hound",
    img: "https://cdn2.thedogapi.com/images/Byz6mgqEQ.jpg",
    height: "53 - 64",
    weight: "53 - 64",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Affectionate",
      "Sociable",
      "Playful",
      "Intelligent",
      "Active",
      "Trainable",
    ],
    breedGroup: "Hound",
    id: 124,
  },
  {
    name: "Plott",
    img: "https://cdn2.thedogapi.com/images/B1i67l5VQ.jpg",
    height: "51 - 64",
    weight: "51 - 64",
    lifeSpan: "12 - 14 years",
    temperaments: ["Bold", "Alert", "Loyal", "Intelligent"],
    breedGroup: "Hound",
    id: 125,
  },
  {
    name: "Pomeranian",
    img: "https://cdn2.thedogapi.com/images/HJd0XecNX.jpg",
    height: "20 - 30",
    weight: "20 - 30",
    lifeSpan: "15 years",
    temperaments: [
      "Extroverted",
      "Friendly",
      "Sociable",
      "Playful",
      "Intelligent",
      "Active",
    ],
    breedGroup: "Toy",
    id: 126,
  },
  {
    name: "Poodle (Miniature)",
    img: "https://cdn2.thedogapi.com/images/Hkxk4ecVX.jpg",
    height: "28 - 38",
    weight: "28 - 38",
    lifeSpan: "12 - 15 years",
    temperaments: [],
    breedGroup: "Unknown",
    id: 127,
  },
  {
    name: "Poodle (Toy)",
    img: "https://cdn2.thedogapi.com/images/rJFJVxc4m.jpg",
    height: "23 - 28",
    weight: "23 - 28",
    lifeSpan: "18 years",
    temperaments: [],
    breedGroup: "Unknown",
    id: 128,
  },
  {
    name: "Pug",
    img: "https://cdn2.thedogapi.com/images/HyJvcl9N7.jpg",
    height: "25 - 30",
    weight: "25 - 30",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Docile",
      "Clever",
      "Charming",
      "Stubborn",
      "Sociable",
      "Playful",
      "Quiet",
      "Attentive",
    ],
    breedGroup: "Toy",
    id: 129,
  },
  {
    name: "Puli",
    img: "https://cdn2.thedogapi.com/images/ryPgVl5N7.jpg",
    height: "41 - 43",
    weight: "41 - 43",
    lifeSpan: "12 - 16 Years years",
    temperaments: [
      "Energetic",
      "Agile",
      "Loyal",
      "Obedient",
      "Intelligent",
      "Faithful",
    ],
    breedGroup: "Herding",
    id: 130,
  },
  {
    name: "Pumi",
    img: "https://cdn2.thedogapi.com/images/SyRe4xcN7.jpg",
    height: "38 - 47",
    weight: "38 - 47",
    lifeSpan: "13 - 15 years",
    temperaments: [
      "Lively",
      "Reserved",
      "Intelligent",
      "Active",
      "Protective",
      "Vocal",
    ],
    breedGroup: "Herding",
    id: 131,
  },
  {
    name: "Rat Terrier",
    img: "https://cdn2.thedogapi.com/images/HkXWNl9E7.jpg",
    height: "25 - 33",
    weight: "25 - 33",
    lifeSpan: "12 - 18 years",
    temperaments: [
      "Affectionate",
      "Lively",
      "Inquisitive",
      "Alert",
      "Intelligent",
      "Loving",
    ],
    breedGroup: "Terrier",
    id: 132,
  },
  {
    name: "Redbone Coonhound",
    img: "https://cdn2.thedogapi.com/images/HJMzEl5N7.jpg",
    height: "53 - 69",
    weight: "53 - 69",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Affectionate",
      "Energetic",
      "Independent",
      "Companionable",
      "Familial",
      "Unflappable",
    ],
    breedGroup: "Hound",
    id: 133,
  },
  {
    name: "Rhodesian Ridgeback",
    img: "https://cdn2.thedogapi.com/images/By9zNgqE7.jpg",
    height: "61 - 69",
    weight: "61 - 69",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Strong Willed",
      "Mischievous",
      "Loyal",
      "Dignified",
      "Sensitive",
      "Intelligent",
    ],
    breedGroup: "Hound",
    id: 134,
  },
  {
    name: "Rottweiler",
    img: "https://cdn2.thedogapi.com/images/r1xXEgcNX.jpg",
    height: "56 - 69",
    weight: "56 - 69",
    lifeSpan: "8 - 10 years",
    temperaments: [
      "Steady",
      "Good-natured",
      "Fearless",
      "Devoted",
      "Alert",
      "Obedient",
      "Confident",
      "Self-assured",
      "Calm",
      "Courageous",
    ],
    breedGroup: "Working",
    id: 135,
  },
  {
    name: "Russian Toy",
    img: "https://cdn2.thedogapi.com/images/HkP7Vxc4Q.jpg",
    height: "19 - 27",
    weight: "19 - 27",
    lifeSpan: "10 - 12 years",
    breedGroup: "Toy",
    temperaments: [],
    id: 136,
  },
  {
    name: "Saint Bernard",
    img: "https://cdn2.thedogapi.com/images/_Qf9nfRzL.png",
    height: "65 - 70",
    weight: "65 - 70",
    lifeSpan: "7 - 10 years",
    temperaments: ["Friendly", "Lively", "Gentle", "Watchful", "Calm"],
    breedGroup: "Working",
    id: 137,
  },
  {
    name: "Saluki",
    img: "https://cdn2.thedogapi.com/images/fjFIuehNo.jpg",
    height: "58 - 71",
    weight: "58 - 71",
    lifeSpan: "12 - 14 years",
    temperaments: ["Aloof", "Reserved", "Intelligent", "Quiet"],
    breedGroup: "Hound",
    id: 138,
  },
  {
    name: "Samoyed",
    img: "https://cdn2.thedogapi.com/images/S1T8Ee9Nm.jpg",
    height: "48 - 60",
    weight: "48 - 60",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Stubborn",
      "Friendly",
      "Sociable",
      "Lively",
      "Alert",
      "Playful",
    ],
    breedGroup: "Working",
    id: 139,
  },
  {
    name: "Schipperke",
    img: "https://cdn2.thedogapi.com/images/SyBvVgc47.jpg",
    height: "25 - 33",
    weight: "25 - 33",
    lifeSpan: "13 - 15 years",
    temperaments: [
      "Fearless",
      "Agile",
      "Curious",
      "Independent",
      "Confident",
      "Faithful",
    ],
    breedGroup: "Non-Sporting",
    id: 140,
  },
  {
    name: "Scottish Deerhound",
    img: "https://cdn2.thedogapi.com/images/SkNjqx9NQ.jpg",
    height: "71 - 81",
    weight: "71 - 81",
    lifeSpan: "8 - 10 years",
    temperaments: ["Docile", "Friendly", "Dignified", "Gentle"],
    breedGroup: "Hound",
    id: 141,
  },
  {
    name: "Scottish Terrier",
    img: "https://cdn2.thedogapi.com/images/Bklnce5NX.jpg",
    height: "25",
    weight: "25",
    lifeSpan: "11 - 13 years",
    temperaments: [
      "Feisty",
      "Alert",
      "Independent",
      "Playful",
      "Quick",
      "Self-assured",
    ],
    breedGroup: "Terrier",
    id: 142,
  },
  {
    name: "Shetland Sheepdog",
    img: "https://cdn2.thedogapi.com/images/rJa29l9E7.jpg",
    height: "33 - 41",
    weight: "33 - 41",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Affectionate",
      "Lively",
      "Responsive",
      "Alert",
      "Loyal",
      "Reserved",
      "Playful",
      "Gentle",
      "Intelligent",
      "Active",
      "Trainable",
      "Strong",
    ],
    breedGroup: "Herding",
    id: 143,
  },
  {
    name: "Shiba Inu",
    img: "https://cdn2.thedogapi.com/images/Zn3IjPX3f.jpg",
    height: "34 - 42",
    weight: "34 - 42",
    lifeSpan: "12 - 16 years",
    temperaments: [
      "Charming",
      "Fearless",
      "Keen",
      "Alert",
      "Confident",
      "Faithful",
    ],
    breedGroup: "Non-Sporting",
    id: 144,
  },
  {
    name: "Shih Tzu",
    img: "https://cdn2.thedogapi.com/images/BkrJjgcV7.jpg",
    height: "20 - 28",
    weight: "20 - 28",
    lifeSpan: "10 - 18 years",
    temperaments: [
      "Clever",
      "Spunky",
      "Outgoing",
      "Friendly",
      "Affectionate",
      "Lively",
      "Alert",
      "Loyal",
      "Independent",
      "Playful",
      "Gentle",
      "Intelligent",
      "Happy",
      "Active",
      "Courageous",
    ],
    breedGroup: "Toy",
    id: 145,
  },
  {
    name: "Shiloh Shepherd",
    img: "https://cdn2.thedogapi.com/images/SJJxjecEX.jpg",
    height: "66 - 76",
    weight: "66 - 76",
    lifeSpan: "9 - 14 years",
    temperaments: [
      "Outgoing",
      "Loyal",
      "Companionable",
      "Gentle",
      "Loving",
      "Trainable",
    ],
    breedGroup: "Unknown",
    id: 146,
  },
  {
    name: "Siberian Husky",
    img: "https://cdn2.thedogapi.com/images/S17ZilqNm.jpg",
    height: "51 - 60",
    weight: "51 - 60",
    lifeSpan: "12 years",
    temperaments: ["Outgoing", "Friendly", "Alert", "Gentle", "Intelligent"],
    breedGroup: "Working",
    id: 147,
  },
  {
    name: "Silky Terrier",
    img: "https://cdn2.thedogapi.com/images/ByzGsl5Nm.jpg",
    height: "23 - 25",
    weight: "23 - 25",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Friendly",
      "Responsive",
      "Inquisitive",
      "Alert",
      "Quick",
      "Joyful",
    ],
    breedGroup: "Toy",
    id: 148,
  },
  {
    name: "Smooth Fox Terrier",
    img: "https://cdn2.thedogapi.com/images/Syszjx9Em.jpg",
    height: "39",
    weight: "39",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Fearless",
      "Affectionate",
      "Alert",
      "Playful",
      "Intelligent",
      "Active",
    ],
    breedGroup: "Terrier",
    id: 149,
  },
  {
    name: "Soft Coated Wheaten Terrier",
    img: "https://cdn2.thedogapi.com/images/HJHmix5NQ.jpg",
    height: "41 - 46",
    weight: "41 - 46",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Affectionate",
      "Spirited",
      "Energetic",
      "Playful",
      "Intelligent",
      "Faithful",
    ],
    breedGroup: "Terrier",
    id: 150,
  },
  {
    name: "Spanish Water Dog",
    img: "https://cdn2.thedogapi.com/images/HJf4jl9VX.jpg",
    height: "41 - 51",
    weight: "41 - 51",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Trainable",
      "Diligent",
      "Affectionate",
      "Loyal",
      "Athletic",
      "Intelligent",
    ],
    breedGroup: "Sporting",
    id: 151,
  },
  {
    name: "Spinone Italiano",
    img: "https://cdn2.thedogapi.com/images/rk5Eoe5Nm.jpg",
    height: "57 - 70",
    weight: "57 - 70",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Docile",
      "Friendly",
      "Affectionate",
      "Loyal",
      "Patient",
      "Gentle",
    ],
    breedGroup: "Sporting",
    id: 152,
  },
  {
    name: "Staffordshire Bull Terrier",
    img: "https://cdn2.thedogapi.com/images/H1zSie9V7.jpg",
    height: "36 - 41",
    weight: "36 - 41",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Reliable",
      "Fearless",
      "Bold",
      "Affectionate",
      "Loyal",
      "Intelligent",
      "Courageous",
    ],
    breedGroup: "Terrier",
    id: 153,
  },
  {
    name: "Standard Schnauzer",
    img: "https://cdn2.thedogapi.com/images/tmzeu6ID_.jpg",
    height: "44 - 50",
    weight: "44 - 50",
    lifeSpan: "13 - 15 years",
    temperaments: [
      "Trainable",
      "Good-natured",
      "Devoted",
      "Lively",
      "Playful",
      "Intelligent",
    ],
    breedGroup: "Working",
    id: 154,
  },
  {
    name: "Swedish Vallhund",
    img: "https://cdn2.thedogapi.com/images/HJ-Dix94Q.jpg",
    height: "29 - 34",
    weight: "29 - 34",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Fearless",
      "Friendly",
      "Energetic",
      "Alert",
      "Intelligent",
      "Watchful",
    ],
    breedGroup: "Herding",
    id: 155,
  },
  {
    name: "Thai Ridgeback",
    img: "https://cdn2.thedogapi.com/images/zv89hR-O8.jpg",
    height: "51 - 61",
    weight: "51 - 61",
    lifeSpan: "10 - 12 years",
    temperaments: [
      "Protective",
      "Loyal",
      "Independent",
      "Intelligent",
      "Loving",
      "Familial",
    ],
    breedGroup: "Hound",
    id: 156,
  },
  {
    name: "Tibetan Mastiff",
    img: "https://cdn2.thedogapi.com/images/SkM9sec47.jpg",
    height: "61 - 66",
    weight: "61 - 66",
    lifeSpan: "10 - 14 years",
    temperaments: [
      "Strong Willed",
      "Tenacious",
      "Aloof",
      "Stubborn",
      "Intelligent",
      "Protective",
    ],
    breedGroup: "Working",
    id: 157,
  },
  {
    name: "Tibetan Spaniel",
    img: "https://cdn2.thedogapi.com/images/Hyjcol947.jpg",
    height: "25",
    weight: "25",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Willful",
      "Aloof",
      "Assertive",
      "Independent",
      "Playful",
      "Intelligent",
      "Happy",
    ],
    breedGroup: "Non-Sporting",
    id: 158,
  },
  {
    name: "Tibetan Terrier",
    img: "https://cdn2.thedogapi.com/images/6f5n_42mB.jpg",
    height: "36 - 43",
    weight: "36 - 43",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Affectionate",
      "Energetic",
      "Amiable",
      "Reserved",
      "Gentle",
      "Sensitive",
    ],
    breedGroup: "Non-Sporting",
    id: 159,
  },
  {
    name: "Toy Fox Terrier",
    img: "https://cdn2.thedogapi.com/images/B17ase9V7.jpg",
    height: "20 - 28",
    weight: "20 - 28",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Friendly",
      "Spirited",
      "Alert",
      "Loyal",
      "Playful",
      "Intelligent",
    ],
    breedGroup: "Toy",
    id: 160,
  },
  {
    name: "Treeing Walker Coonhound",
    img: "https://cdn2.thedogapi.com/images/SkRpsgc47.jpg",
    height: "51 - 69",
    weight: "51 - 69",
    lifeSpan: "10 - 13 years",
    temperaments: [
      "Clever",
      "Affectionate",
      "Confident",
      "Intelligent",
      "Loving",
      "Trainable",
    ],
    breedGroup: "Hound",
    id: 161,
  },
  {
    name: "Vizsla",
    img: "https://cdn2.thedogapi.com/images/r1o0jx9Em.jpg",
    height: "53 - 61",
    weight: "53 - 61",
    lifeSpan: "10 - 14 years",
    temperaments: ["Affectionate", "Energetic", "Loyal", "Gentle", "Quiet"],
    breedGroup: "Sporting",
    id: 162,
  },
  {
    name: "Weimaraner",
    img: "https://cdn2.thedogapi.com/images/SyU12l9V7.jpg",
    height: "58 - 69",
    weight: "58 - 69",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Steady",
      "Aloof",
      "Stubborn",
      "Energetic",
      "Alert",
      "Intelligent",
      "Powerful",
      "Fast",
    ],
    breedGroup: "Sporting",
    id: 163,
  },
  {
    name: "Welsh Springer Spaniel",
    img: "https://cdn2.thedogapi.com/images/BJ1gnx5Vm.jpg",
    height: "43 - 48",
    weight: "43 - 48",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Stubborn",
      "Friendly",
      "Affectionate",
      "Loyal",
      "Playful",
      "Active",
    ],
    breedGroup: "Sporting",
    id: 164,
  },
  {
    name: "West Highland White Terrier",
    img: "https://cdn2.thedogapi.com/images/Bkdx2g5Em.jpg",
    height: "25 - 28",
    weight: "25 - 28",
    lifeSpan: "15 - 20 years",
    temperaments: [
      "Hardy",
      "Friendly",
      "Alert",
      "Independent",
      "Gay",
      "Active",
      "Courageous",
    ],
    breedGroup: "Terrier",
    id: 165,
  },
  {
    name: "Whippet",
    img: "https://cdn2.thedogapi.com/images/Hyv-ne94m.jpg",
    height: "46 - 56",
    weight: "46 - 56",
    lifeSpan: "12 - 15 years",
    temperaments: [
      "Friendly",
      "Affectionate",
      "Lively",
      "Gentle",
      "Intelligent",
      "Quiet",
    ],
    breedGroup: "Hound",
    id: 166,
  },
  {
    name: "White Shepherd",
    img: "https://cdn2.thedogapi.com/images/r14M3e9E7.jpg",
    height: "56 - 64",
    weight: "56 - 64",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Self-confidence",
      "Aloof",
      "Fearless",
      "Alert",
      "Companionable",
      "Eager",
    ],
    breedGroup: "Unknown",
    id: 167,
  },
  {
    name: "Wire Fox Terrier",
    img: "https://cdn2.thedogapi.com/images/SJ6f2g9EQ.jpg",
    height: "33 - 41",
    weight: "33 - 41",
    lifeSpan: "13 - 14 years",
    temperaments: ["Fearless", "Friendly", "Bold", "Keen", "Alert", "Quick"],
    breedGroup: "Unknown",
    id: 168,
  },
  {
    name: "Wirehaired Pointing Griffon",
    img: "https://cdn2.thedogapi.com/images/Bkam2l9Vm.jpg",
    height: "51 - 61",
    weight: "51 - 61",
    lifeSpan: "12 - 14 years",
    temperaments: ["Loyal", "Gentle", "Vigilant", "Trainable", "Proud"],
    breedGroup: "Sporting",
    id: 169,
  },
  {
    name: "Wirehaired Vizsla",
    img: "https://cdn2.thedogapi.com/images/r1I4hl5Em.jpg",
    height: "55 - 64",
    weight: "55 - 64",
    lifeSpan: "12 - 14 years",
    breedGroup: "Sporting",
    temperaments: [],
    id: 170,
  },
  {
    name: "Xoloitzcuintli",
    img: "https://cdn2.thedogapi.com/images/HkNS3gqEm.jpg",
    height: "25 - 58",
    weight: "25 - 58",
    lifeSpan: "12 - 14 years",
    temperaments: [
      "Cheerful",
      "Alert",
      "Companionable",
      "Intelligent",
      "Protective",
      "Calm",
    ],
    breedGroup: "Non-Sporting",
    id: 171,
  },
  {
    name: "Yorkshire Terrier",
    img: "https://cdn2.thedogapi.com/images/B12BnxcVQ.jpg",
    height: "20 - 23",
    weight: "20 - 23",
    lifeSpan: "12 - 16 years",
    temperaments: [
      "Bold",
      "Independent",
      "Confident",
      "Intelligent",
      "Courageous",
    ],
    breedGroup: "Toy",
    id: 172,
  },
];

export default data;
